### ISSUE TITLE
How to define resize/drag callback?

### ISSUE THREAD

**Issue by rmitsch** [BusinessOptics/dash_split_pane#9]
I'm currently trying to adjust the size of contained figures when the size of my split pane changes. I couldn't figure out how to implement the callback - which events/properties do I have to listen to?

I tried with 
```
    @app.callback(
        dash.dependencies.Output('splitter_execeditor_kpis', 'size'),
        dash.dependencies.Input('kpis', 'children')
    )
    def update(value):
        print(value)
```
which doesn't fire on resize/drag events.

Thanks!

**Comment by JHSaunders** [comment]
Hi,

Th `usage.py` shows an example of this, you should listen to the `size` property:

```python
import dash_split_pane
import dash
from dash.dependencies import Input, Output
import dash_html_components as html

app = dash.Dash(__name__)

app.layout = html.Div(
    [
        dash_split_pane.DashSplitPane(
            children=[html.Div(id="left-pane"), html.Div("RIGHT PANE")],
            id="splitter",
            split="vertical",
            size=50,
            persistence=True,
        ),
    ]
)


@app.callback(Output("left-pane", "children"), [Input("splitter", "size")])
def show_size(size):
    return size


if __name__ == "__main__":
    app.run_server(debug=True)
````
It looks like you have confused your Input and Output in your example, and are not really returning a value.

Also please note that the callback is only fired once dragging is completed. This is intentional as firing off a callback fro every drag moment would overwhelm dash with callbacks that have to be sent back to the server.

**Comment by rmitsch** [comment]
Ah, of course. Thanks for the swift response!
